routes/web.php
<?php

// |||||||||||||||||WebView|||||||||||||||||||||
Auth::routes();
Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
	Route::get('/login/callback/{social}', 'SocialAuthController@handleProviderCallback');
	Route::get('/login/{social}', 'SocialAuthController@redirectToProvider');
});
Route::get('/', 'HomeController@index');
Route::get('/category/{name}', 'HomeController@byCategory');
Route::get('/related-products/{categoryId}', 'HomeController@relatedProducts');
Route::get('/detail/{product}', 'HomeController@detail')->name('product.detail');
Route::get('/search', 'HomeController@search')->name('search');
//static
Route::get('/help', 'HomeController@help')->name('help');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/return-policy', 'HomeController@returnPolicy')->name('return-policy');
//cart
Route::get('/cart', 'CartsController@cart');
Route::get('/cart/add/{manage}', 'CartsController@add');
Route::get('/cart/update/{rowId}/{quantity}', 'CartsController@update');
Route::get('/cart/delete/{rowId}', 'CartsController@delete');
Route::get('/cart/destroy', 'CartsController@destroy');

Route::get('/my-cart', 'CartsController@myCart')->name('my-cart');

Route::middleware(['auth'])->group(function () {
	Route::get('/shipping', 'CheckoutsController@shipping')->name('shipping');
	Route::post('/shipping', 'CheckoutsController@storeShipping')->name('shipping.store');
	Route::get('/payment', 'CheckoutsController@payment')->name('payment');
	Route::post('/payment', 'CheckoutsController@storePayment');
	Route::get('/review-order', 'CheckoutsController@reviewOrder')->name('review-order');
	Route::post('/confirm-order', 'CheckoutsController@confirmOrder')->name('confirm-order');
	Route::get('/order-history', 'OrderHistoriesController@orderHistory')->name('order-history');
	Route::get('/order-history/details/{order}', 'OrderHistoriesController@orderDetails')->name('order-history.details');
	Route::get('/user/settings', 'SettingsController@index')->name('settings');
	Route::post('/user/settings', 'SettingsController@updateUser')/*->name('update-user')*/;
 });






// |||||||||||||||||||||admin routes|||||||||||||||||||
Route::prefix('backend')->group(function () {
	Route::get('dashboard', 'BackendController@index')->name('backend');
	Route::get('home', 'BackendController@index');

	Route::resource('categories', 'CategoriesController');

	Route::delete('products/{image}/gallery/remove', 'ProductsController@remove')->name('products.gallery.remove');
	Route::match(['get', 'post'], 'products/{product}/gallery', 'ProductsController@gallery')->name('products.gallery');
	Route::resource('products', 'ProductsController');

	Route::get('product/manage/create/{product}', 'ManageProductsController@create')->name('manage.create');
	Route::get('product/manage/{product}', 'ManageProductsController@show')->name('manage.show');
	Route::get('product/manage/{manage}/increase', 'ManageProductsController@increase')->name('manage.increase');
	Route::resource('product/manage', 'ManageProductsController', ['except' => ['create', 'index', 'show']]);

	Route::resource('product-entry-records', 'ProductEntryRecordsController');

	Route::get('customer-orders/{customer_order}/shipping', 'OrdersController@shipping')->name('customer-orders.shipping');
	Route::resource('customer-orders', 'OrdersController');

	// Route::get('add-product', 'ProductsController@create');

});

Route::get('/home', 'HomeController@index')->name('home');

app/Product.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
	protected $guarded = [];

	public function images()
    {
        return $this->hasMany(\App\ProductImage::class);
    }

	public function manage()
    {
        return $this->hasMany(\App\ManageProduct::class);
    }

	public function category()
    {
        return $this->belongsTo(\App\Category::class);
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
   public function index()
   {
   		return view('backend.home');   
   }

}

app/Http/Controllers/ProductsController.php
<?php

namespace App\Http\Controllers;

use App\Product;
use App\ProductImage;
use Illuminate\Http\Request;
use Intervention\Image\ImageManagerStatic as Image;


class ProductsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $title = "All Products";
        $products = Product::with('category')->latest()->paginate(111);

        return view('backend.Products.index', compact('products', 'title'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {        
        $categories = \App\Category::all();
        return view('backend.Products.create', compact('categories'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @return \Illuminate\Http\Response
     */

    public function store()
    {
        $this->validateWhileCreate();
       
        $frontImage = $this->storeImage(request('front_image'), '/images/products/front/', 230, 230);
        $thumbImage = $this->storeImage(request('front_image'), '/images/products/thumb/', 60, 60);
        $largeImage = $this->storeImage(request('front_image'), '/images/products/large/', 800, 800);
        
        $product = Product::create([
                'category_id' => request('category_id'),
                'title'       => request('title'),
                'description' => request('description'),
                'front_price' => request('front_price'),
                'front_discount' => request('front_discount'),
                'front_image' => $frontImage,
                            ])->images()->create([
                                    'large_image' => $largeImage, 
                                    'thumb_image' => $thumbImage
                                ]);

        return back()->with("success", "Successfully created product {$product->title}");        
    }

    /**
     * Validating a newly created Product data. 
     */
    public function validateWhileCreate()
    {
        $this->validate(request(), [
                "category_id" => "required|integer",
                "title" => "required",
                "description" => "required",
                "front_price" => "required|numeric",
                "front_discount" => "nullable|numeric|max:".request('front_price'),
                // "front_image" => "required|image|max:1500|dimensions:ratio=1/1",
                "front_image" => "required|image|max:1500",
            ], [
                "category_id.required" => "A Category is Required"
            ]);
    }

    /**
    * Store file
    * @param $file  request()->file('name')
    * @param $location  image location with forward slashes
    * @param $width  width of the resized image
    * @param $height  width of the resized image
    * @return path to the saved image
    *
    */
    public function storeImage($file, $location, $width, $height)
    {        
        $ext= $file->guessClientExtension();
        $path = trim($location, '/').'/'.time().str_random(10). '.' . $ext;
        // ini_set('memory_limit','500M');
        if(Image::make($file)
                ->resize($width, $height)
                ->save($path)
            )
            return $path;
    }

    

    /**
     * Display the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function show(Product $product)
    {

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function edit(Product $product)
    {
        // dd($product);
        $categories = \App\Category::all();
        return view('backend.Products.edit', compact('categories', 'product'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function update(Product $product)
    {
        $this->ValidateWhileUpadte();
        $product->category_id = request('category_id');
        $product->title = request('title');
        $product->description = request('description');
        $product->front_price = request('front_price');
        $product->front_discount = request('front_discount');
        if(request()->hasFile('front_image'))
        {
            if(file_exists($product->front_image)) 
                unlink($product->front_image);         
            $product->front_image 
            = $this->storeImage(request('front_image'), '/images/products/front/', 230, 230);
        }
        $product->save();

        return redirect()
                ->route('products.index')
                ->with('success', "successfully updated product {$product->title}");
    }

    /**
     * Validation for Product Update. 
     */
    public function ValidateWhileUpadte()
    {
        $this->validate(request(), [
                "category_id" => "required|integer",
                "title" => "required",
                "description" => "required",
                "front_price" => "required|numeric",
                "front_discount" => "nullable|numeric|max:".request('front_price'),
                // "front_image" => "image|max:1500|dimensions:ratio=1/1",
                "front_image" => "image|max:1500",
            ], [
                "category_id.required" => "A Category is Required"
            ]);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Product  $product
     * @return \Illuminate\Http\Response
     */
    public function destroy(Product $product)
    {
        return "this functionality is pending";
    }

    public function gallery(Product $product)
    {
        if(request()->ajax())
        {
            if( request()->hasFile('image'))
            {
                $this->validate(request(), [
                    'image' => 'required|image|max:1500',
                    ]);

                $image = \App\ProductImage::create([
                    'product_id' => $product->id,
                    'large_image' => $this->storeImage(request('image'), '/images/products/large/', 800, 800),
                    'thumb_image' => $this->storeImage(request('image'), '/images/products/thumb/', 60, 60),
                ]);
                return response()
                    ->json([
                        'message' => 'Successfully uploaded Gallery Image',
                        'src'   => '
                                  <div class="col-md-2" id="image_' . $image->id . '">
                                    <div class="thumbnail relative">              
                                        <img src="' . asset($image->large_image) . '" style="width:100%">
                                        <div class="caption text-center">                
                                          <span href="#" class="abs-btn" onclick="remove_image(\''. route('products.gallery.remove', ['image' => $image->id ]) . '\', \'#image_' . $image->id . '\')"><i class="fa fa-trash fa-2x text-red"></i></span>               
                                        </div>              
                                    </div>
                                  </div>', 
                     ]);
            }
            
        }
        $title = "Manage Gallery";
        $product->load('images');
        // dd($product);
        return view('backend.Products.gallery', compact('product', 'title'));
    }

    public function remove(ProductImage $image)
    {
        if(request()->ajax())
        {
            if($image->delete())
            {
                if(file_exists($image->large_image)) 
                    unlink($image->large_image); 
                if(file_exists($image->thumb_image)) 
                    unlink($image->thumb_image); 
                return response()
                       ->json(['message' => "Successfully deleted"]);
            }
            return response()
                       ->json(['message' => "error"]);    
        }
    }
}

resources/views/backend/Products/add.blade.php
@extends('backend.layout.master')

@section('title', 'Products')


@section('main-content') 
@push('css')
@endpush




<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">Products</h3>


  </div>
         
  <div class="box-body">
    <img src="{{ asset('/images/products/front/1501568436LZtcTYMEXZ.jpeg')}}">
    <img src="/images/products/front/1501568436LZtcTYMEXZ.jpeg">
    {{ asset('/images/products/front/1501568436LZtcTYMEXZ.jpeg')}}
    <br>
    /images/products/front/1501568436LZtcTYMEXZ.jpeg

  </div>
</div>



@push('scripts')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/full/ckeditor.js"></script>

<script>
  $(function () {
    // Replace the <textarea id="description"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('description');
  });
</script>
@endpush
@endsection

resources/views/backend/Products/create.blade.php
@extends('backend.layout.master')

@section('title', 'Products')


@section('main-content')
@push('css')
@endpush


<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">Add Product</h3>

  </div>
         
  <div class="box-footer">
    <form method="post" action="{{ route('products.store') }}" enctype="multipart/form-data">
      
      {{ csrf_field() }}


        @include('Element.Form.bs-select', [
            'name' => 'category_id', 
            'label' => 'Category', 
            'required' => 'required', 
            'help' => '', 
            'options' => $categories, 
            'val' => 'id', 
            'show' => 'name'
          ])

        @include('Element.Form.bs-input', [
            'name' => 'title', 
            'required' => 'required', 
            'help' => ''
          ])

        @include('Element.Form.bs-input', [
            'name' => 'front_price',
            'label' => 'Price',
            'help'  => 'Price to be displayed in Front',
            'type' => 'number',
            'required' => 'required',
            'attr' => 'min=1 step=0.01'
          ])

        @include('Element.Form.bs-input', [
            'name' => 'front_discount',
            'label' => 'Discount',
            'help' => 'Discount to be displayed in Front',
            'type' => 'number',
            'attr' => 'min=1 step=0.01'
          ])

        @include('Element.Form.bs-input', [
            'name' => 'front_image', 
            'type' => 'file', 
            'required' => 'required', 
            'attr' => 'accept=image/*'
          ])
        
        @include('Element.Form.bs-textarea', [
            'name' => 'description', 
            'required' => 'required', 
            'help' => ''
          ])

        <div class="form-group">
          <button type="submit" class="btn btn-success"><i class="fa fa-plus"> Add Product</i></button>
        </div>

      </form>
  </div>
</div>


@push('scripts')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/full/ckeditor.js"></script>

<script>
  $(function () {
    // Replace the <textarea id="description"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('description');
  });
</script>
@endpush
@endsection

resources/views/backend/Products/edit.blade.php
@extends('backend.layout.master')

@section('title', 'Products')


@section('main-content')
@push('css')
@endpush



<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">Update Product</h3>

  </div>
         
  <div class="box-body">
    <div class="col-md-3 pull-right">
      <img class="img-responsive pull-right" src="{{ asset($product->front_image) }}">
    </div>
    <form method="post" action="{{ route('products.update', [ 'products' => $product->id ]) }}" enctype="multipart/form-data">
      
      {{ csrf_field() }}

      {{ method_field('PATCH') }}

      <div class="col-md-9">
        @include('Element.Form.bs-select', [
            'name' => 'category_id', 
            'label' => 'Category', 
            'value' => $product->category_id, 
            'required' => 'required', 
            'help' => '', 
            'options' => $categories, 
            'val' => 'id', 
            'show' => 'name'
          ])
        @include('Element.Form.bs-input', [
            'name' => 'title', 
            'required' => 'required', 
            'value' => $product->title, 
            'help' => ''
          ])
        @include('Element.Form.bs-input', [
            'name' => 'front_price',
            'label' => 'Price',
            'value' => $product->front_price, 
            'help'  => 'Price to be displayed in Front',
            'type' => 'number',
            'required' => 'required',
            'attr' => 'min=1 step=0.01'
          ])
        @include('Element.Form.bs-input', [
            'name' => 'front_discount',
            'label' => 'Discount',
            'value' => $product->front_discount,
            'help' => 'Discount to be displayed in Front',
            'type' => 'number',
            'attr' => 'min=1 step=0.01'
          ])
        @include('Element.Form.bs-input', [
            'name' => 'front_image', 
            'type' => 'file',
            'attr' => 'accept=image/*',
            'help' => 'Image should be square in dimention and Max 1.5 MB'
          ])
      </div>

      <div class="col-md-12">      
        @include('Element.Form.bs-textarea', [
            'name' => 'description', 
            'value' => $product->description,
            'required' => 'required', 
            'help' => ''
          ])
        <div class="form-group">
          <button type="submit" class="btn btn-success"><i class="fa fa-edit"> Update Product</i></button>
        </div>
      </div>

      </form>
  </div>
</div>


@push('scripts')
<!-- CK Editor -->
<script src="https://cdn.ckeditor.com/4.5.7/full/ckeditor.js"></script>

<script>
  $(function () {
    // Replace the <textarea id="description"> with a CKEditor
    // instance, using default configuration.
    CKEDITOR.replace('description');
  });
</script>
@endpush
@endsection

resources/views/backend/Products/gallery.blade.php
@extends('backend.layout.master')

@section('title', $title)

@section('main-content')

@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/dropzone/dropzone.css">
<style type="text/css">
  .relative {position: relative;}
  .abs-btn {position: absolute; top: 5px; right: 5px; background: transparent; cursor: pointer;}
</style>

@endpush


<div class="box">
    <div class="box-header">
        <h3 class="box-title">{{ $title }}</h3>
    </div>
    <!-- /.box-header -->
    <div class="box-body">
      <div class="col-md-12">
        <form id="productGallery" class="dropzone" action="{{ url()->current() }}" method="post" enctype="multipart/form-data">
            {{ csrf_field() }}
        </form>
      </div>

      <div class="col-md-12">
         <div class="row" id="product_gallery">

         @foreach($product->images as $image)
          <div class="col-md-2" id="image_{{ $image->id }}">
            <div class="thumbnail relative">
                <img src="{{ asset($image->large_image) }}" alt="Fjords" style="width:100%">
                <div class="caption text-center">
                  <span href="#" class="abs-btn" onclick="remove_image('{{ route('products.gallery.remove', ['image' => $image->id ]) }}', '#image_{{ $image->id }}')"><i class="fa fa-trash fa-2x text-red"></i></span>
                </div>
            </div>
          </div>
          @endforeach

        </div>
      </div>

    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->


@push('scripts')
<!-- DataTables -->
<script src="{{asset('admin_assets')}}/plugins/dropzone/dropzone.js"></script>
<script type="text/javascript">
  Dropzone.options.productGallery = {
  paramName: "image",
  uploadMultiple: false,
  // thumbnailWidth: 200,
  // thumbnailHeight: 200,
  maxFiles: 5,
  acceptedFiles: 'image/*',
  maxFilesize: 2, // MB
  // addRemoveLinks: true, //||||||||||||||||||
  init: function() {
   //  this.on("removedfile", function(file) {
   //    x = confirm('Do you want to delete?');
   //    if(!x)  return false;
   // });
    this.on("success", function(file, response){

            // obj = JSON.parse(response);
            alert(response.message);
            $("#product_gallery").append(response.src);
    });
    this.on("error", function(file, response){

            // obj = JSON.parse(response);
            alert(response.image);
            $(file.previewElement).find('.dz-error-message').text(response.image);

    })
  },
};
</script>
<script type="text/javascript">
  function remove_image(link, id){
    $.ajax({
      type: "POST",
      url: link,
      data: { "_method" : "DELETE", "_token" : "{{ csrf_token() }}" },
      success: function( response ){
         alert(response.message);
         if (response.message != "error") {
          $(id).remove();
         }
      },
    });
  }
</script>
@endpush
@endsection

resources/views/backend/Products/index.blade.php
@extends('backend.layout.master')

@section('title', $title)

@section('main-content') 

@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.css">
<style type="text/css">
    th { vertical-align: top; }
</style>
@endpush


<div class="box">
    <div class="box-header">
        <h3 class="box-title">{{ $title }}</h3>

        <a href="{{ route('products.create') }}" class="btn btn-success pull-right"><span class="fa fa-plus"></span>&nbsp;&nbsp; Add Product</a>

    </div>
    <!-- /.box-header -->
    <div class="box-body">

    

        <table id="example1" class="table table-bordered table-striped text-center">
            <thead>
                <tr class="">
                    <th>ID</th>
                    <th>Product Title</th>
                    <th>Image</th>
                    <th>Category</th>
                    <th>Price (Front)</th>
                    <th>Discount (Front)</th>
                    <th>Status</th>
                    <th>Stock Status</th>
                    <th width="200">Actions</th>
                </tr>
            </thead>
            <tbody>
                @if($products)
                @foreach($products as $product)

                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->title }}</td>
                    <td><img src="{{ asset($product->front_image) }}" width="40" /></td>
                    <td>{{ $product->category->name }}</td>
                    <td>{{ $product->front_price }}</td>
                    <td>{{ $product->front_discount }}</td>
                    <td>{!! ($product->status == 1) ? "<label class='label bg-green'>Active</label>" : "<label class='label bg-red'>Inactive</label>" !!}</td>
                    <td>{!! ($product->stock_status == 0) ? "<label class='label bg-red'>Out of Stock</label>" : "<label class='label bg-green'>In Stock</label>" !!}</td>
                    <td>
                    <div class="col-sm-8">
                     {{-- <form class="form-inline" action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                        {{ csrf_field() }}
                        {{ method_field('DELETE') }}
                        <button type="submit" class="btn-sm btn-danger pull-right edit" onclick="return confirm('Are you sure')">
                            <i class="glyphicon glyphicon-edit"></i> Delete
                        </button>
                     </form> --}}
                   </div>
                      <a href="{{ route('products.edit', ['product' => $product->id]) }}" class="btn-sm btn-primary pull-right edit">
                          <i class="glyphicon glyphicon-edit"></i> Edit
                      </a>
                      <a href="{{ route('manage.show', ['product' => $product->id]) }}" class="btn-sm btn-warning pull-right edit">
                          <i class="glyphicon glyphicon-edit"></i> Manage
                      </a>
                      <a href="{{ route('products.gallery', ['product' => $product->id]) }}" class="btn-sm btn-success pull-right edit">
                          <i class="glyphicon glyphicon-edit"></i> Gallery
                      </a>
                      {{-- <a href="http://localhost:8001/admin/posts/1" class="btn-sm btn-warning pull-right">
                          <i class="glyphicon glyphicon-eye-open"></i> View
                      </a> --}}
                    </td>
                    
                </tr>
                @endforeach
                @endif


            </tbody>

        </table>
     
        <div class="text-center">{{ $products->links() }}</div>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->


@push('scripts')
<!-- DataTables -->
<script src="{{asset('admin_assets')}}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- page script -->
<script>
        $(function () {
        // $("#example1").DataTable();
          $('#example1').DataTable({
          "paging": false,
                  "lengthChange": false,
                  "searching": true,
                  "ordering": true,
                  "info": true,
                  "autoWidth": false,
                  "columns": [
                  { "searchable": true },
                  { "searchable": true },
                  { "searchable": false },
                  { "searchable": true },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  ]
          });

        });
</script>
@endpush
@endsection