routes/web.php
<?php

// |||||||||||||||||WebView|||||||||||||||||||||
Auth::routes();
Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
	Route::get('/login/callback/{social}', 'SocialAuthController@handleProviderCallback');
	Route::get('/login/{social}', 'SocialAuthController@redirectToProvider');
});
Route::get('/', 'HomeController@index');
Route::get('/category/{name}', 'HomeController@byCategory');
Route::get('/related-products/{categoryId}', 'HomeController@relatedProducts');
Route::get('/detail/{product}', 'HomeController@detail')->name('product.detail');
Route::get('/search', 'HomeController@search')->name('search');
//static
Route::get('/help', 'HomeController@help')->name('help');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/return-policy', 'HomeController@returnPolicy')->name('return-policy');
//cart
Route::get('/cart', 'CartsController@cart');
Route::get('/cart/add/{manage}', 'CartsController@add');
Route::get('/cart/update/{rowId}/{quantity}', 'CartsController@update');
Route::get('/cart/delete/{rowId}', 'CartsController@delete');
Route::get('/cart/destroy', 'CartsController@destroy');

Route::get('/my-cart', 'CartsController@myCart')->name('my-cart');

Route::middleware(['auth'])->group(function () {
	Route::get('/shipping', 'CheckoutsController@shipping')->name('shipping');
	Route::post('/shipping', 'CheckoutsController@storeShipping')->name('shipping.store');
	Route::get('/payment', 'CheckoutsController@payment')->name('payment');
	Route::post('/payment', 'CheckoutsController@storePayment');
	Route::get('/review-order', 'CheckoutsController@reviewOrder')->name('review-order');
	Route::post('/confirm-order', 'CheckoutsController@confirmOrder')->name('confirm-order');
	Route::get('/order-history', 'OrderHistoriesController@orderHistory')->name('order-history');
	Route::get('/order-history/details/{order}', 'OrderHistoriesController@orderDetails')->name('order-history.details');
	Route::get('/user/settings', 'SettingsController@index')->name('settings');
	Route::post('/user/settings', 'SettingsController@updateUser')/*->name('update-user')*/;
 });






// |||||||||||||||||||||admin routes|||||||||||||||||||
Route::prefix('backend')->group(function () {
	Route::get('dashboard', 'BackendController@index')->name('backend');
	Route::get('home', 'BackendController@index');

	Route::resource('categories', 'CategoriesController');

	Route::delete('products/{image}/gallery/remove', 'ProductsController@remove')->name('products.gallery.remove');
	Route::match(['get', 'post'], 'products/{product}/gallery', 'ProductsController@gallery')->name('products.gallery');
	Route::resource('products', 'ProductsController');

	Route::get('product/manage/create/{product}', 'ManageProductsController@create')->name('manage.create');
	Route::get('product/manage/{product}', 'ManageProductsController@show')->name('manage.show');
	Route::get('product/manage/{manage}/increase', 'ManageProductsController@increase')->name('manage.increase');
	Route::resource('product/manage', 'ManageProductsController', ['except' => ['create', 'index', 'show']]);

	Route::resource('product-entry-records', 'ProductEntryRecordsController');

	Route::get('customer-orders/{customer_order}/shipping', 'OrdersController@shipping')->name('customer-orders.shipping');
	Route::resource('customer-orders', 'OrdersController');

	// Route::get('add-product', 'ProductsController@create');

});

Route::get('/home', 'HomeController@index')->name('home');

resources/views/backend/layout/partials/contentheader.blade.php
<!-- Content Header (Page header) -->
    <!-- <section class="content-header">
      <h1>
        Page Header
        <small>Optional description</small>
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Level</a></li>
        <li class="active">Here</li>
      </ol>
    </section> -->

resources/views/backend/layout/partials/controlsidebar.blade.php
<!-- Control Sidebar -->
  <aside class="control-sidebar control-sidebar-dark">
    <!-- Create the tabs -->
    <ul class="nav nav-tabs nav-justified control-sidebar-tabs">
      <li class="active"><a href="#control-sidebar-home-tab" data-toggle="tab"><i class="fa fa-home"></i></a></li>
      <li><a href="#control-sidebar-settings-tab" data-toggle="tab"><i class="fa fa-gears"></i></a></li>
    </ul>
    <!-- Tab panes -->
    <div class="tab-content">
      <!-- Home tab content -->
      <div class="tab-pane active" id="control-sidebar-home-tab">
        <h3 class="control-sidebar-heading">Recent Activity</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <i class="menu-icon fa fa-birthday-cake bg-red"></i>

              <div class="menu-info">
                <h4 class="control-sidebar-subheading">Langdon's Birthday</h4>

                <p>Will be 23 on April 24th</p>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

        <h3 class="control-sidebar-heading">Tasks Progress</h3>
        <ul class="control-sidebar-menu">
          <li>
            <a href="javascript::;">
              <h4 class="control-sidebar-subheading">
                Custom Template Design
                <span class="pull-right-container">
                  <span class="label label-danger pull-right">70%</span>
                </span>
              </h4>

              <div class="progress progress-xxs">
                <div class="progress-bar progress-bar-danger" style="width: 70%"></div>
              </div>
            </a>
          </li>
        </ul>
        <!-- /.control-sidebar-menu -->

      </div>
      <!-- /.tab-pane -->
      <!-- Stats tab content -->
      <div class="tab-pane" id="control-sidebar-stats-tab">Stats Tab Content</div>
      <!-- /.tab-pane -->
      <!-- Settings tab content -->
      <div class="tab-pane" id="control-sidebar-settings-tab">
        <form method="post">
          <h3 class="control-sidebar-heading">General Settings</h3>

          <div class="form-group">
            <label class="control-sidebar-subheading">
              Report panel usage
              <input type="checkbox" class="pull-right" checked>
            </label>

            <p>
              Some information about this general settings option
            </p>
          </div>
          <!-- /.form-group -->
        </form>
      </div>
      <!-- /.tab-pane -->
    </div>
  </aside>
  <!-- /.control-sidebar -->
  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>

resources/views/backend/layout/partials/flash-messages.blade.php
@if(session('warning'))
    <div class="alert alert-xs alert-warning"><strong>{{ session('warning') }}</strong></div>
@endif

@if(session('success'))
    <div class="alert alert-xs alert-success"><strong>{{ session('success') }}</strong></div>
@endif

@if(session('danger'))
    <div class="alert alert-xs alert-danger"><strong>{{ session('danger') }}</strong></div>
@endif

resources/views/backend/layout/partials/htmlheader.blade.php
<head>
    <meta charset="utf-8">

    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>@yield('title', ' Admin') </title>
    <!-- Tell the browser to be responsive to screen width -->
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <link rel="shortcut icon" href="/favicon.ico">
    <!-- Bootstrap 3.3.6 -->
    <link rel="stylesheet" href="{{asset('admin_assets')}}/bootstrap/css/bootstrap.min.css">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
    <!-- Ionicons -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="{{asset('admin_assets')}}/dist/css/AdminLTE.min.css">
    <!-- AdminLTE Skins. We have chosen the skin-blue for this starter
          page. However, you can choose any other skin. Make sure you
          apply the skin class to the body tag so the changes take effect.
    -->
    <link rel="stylesheet" href="{{asset('admin_assets')}}/dist/css/skins/skin-blue.min.css">
    <!-- jQuery 2.2.3 -->
    <script src="{{asset('admin_assets')}}/plugins/jQuery/jquery-2.2.3.min.js"></script>

    @stack('css')

    <!-- Bootstrap 3.3.6 -->
    <script src="{{asset('admin_assets')}}/bootstrap/js/bootstrap.min.js"></script>
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <script>
  window.Laravel = {!! json_encode([
          'csrfToken' => csrf_token(),
  ]) !!}
  ;
    </script>
</head>

resources/views/backend/layout/partials/mainfooter.blade.php
<!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Anything you want
    </div>
    <!-- Default to the left -->
    <strong>Copyright &copy; 2016 <a href="#">Company</a>.</strong> All rights reserved.
  </footer>

resources/views/backend/layout/partials/mainheader.blade.php
<!-- Main Header -->
<header class="main-header">

    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>BIXOP</b></span>
    </a>

    <!-- Header Navbar -->
    <nav class="navbar navbar-static-top" role="navigation">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>
      <!-- Navbar Right Menu -->
      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">
          <!-- Messages: style can be found in dropdown.less-->
          {{--<li class="dropdown messages-menu">
            <!-- Menu toggle button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-envelope-o"></i>
              <span class="label label-success">4</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 4 messages</li>
              <li>
                <!-- inner menu: contains the messages -->
                <ul class="menu">
                  <li><!-- start message -->
                    <a href="#">
                      <div class="pull-left">
                        <!-- User Image -->
                        <img src="{{asset('public/admin_assets')}}/dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
                      </div>
                      <!-- Message title and timestamp -->
                      <h4>
                        Support Team
                        <small><i class="fa fa-clock-o"></i> 5 mins</small>
                      </h4>
                      <!-- The message -->
                      <p>Why not buy a new awesome theme?</p>
                    </a>
                  </li>
                  <!-- end message -->
                </ul>
                <!-- /.menu -->
              </li>
              <li class="footer"><a href="#">See All Messages</a></li>
            </ul>
          </li>
          <!-- /.messages-menu -->

          <!-- Notifications Menu -->
          <li class="dropdown notifications-menu">
                                <!-- Menu toggle button -->
                                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                  <i class="fa fa-bell-o"></i>
                                  <span class="label label-warning">10</span>
                                </a>
                                <ul class="dropdown-menu">
                                  <li class="header">You have 10 notifications</li>
                                  <li>
                                    Inner Menu: contains the notifications
                                    <ul class="menu">
                                      <li><!-- start notification -->
                                        <a href="#">
                                          <i class="fa fa-users text-aqua"></i> 5 new members joined today
                                        </a>
                                      </li>
                                      <!-- end notification -->
                                    </ul>
                                  </li>
                                  <li class="footer"><a href="#">View all</a></li>
                                </ul>
                              </li>
          <!-- Tasks Menu -->
          <li class="dropdown tasks-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <i class="fa fa-flag-o"></i>
              <span class="label label-danger">9</span>
            </a>
            <ul class="dropdown-menu">
              <li class="header">You have 9 tasks</li>
              <li>
                <!-- Inner menu: contains the tasks -->
                <ul class="menu">
                  <li><!-- Task item -->
                    <a href="#">
                      <!-- Task title and progress text -->
                      <h3>
                        Design some buttons
                        <small class="pull-right">20%</small>
                      </h3>
                      <!-- The progress bar -->
                      <div class="progress xs">
                        <!-- Change the css width attribute to simulate progress -->
                        <div class="progress-bar progress-bar-aqua" style="width: 20%" role="progressbar" aria-valuenow="20" aria-valuemin="0" aria-valuemax="100">
                          <span class="sr-only">20% Complete</span>
                        </div>
                      </div>
                    </a>
                  </li>
                  <!-- end task item -->
                </ul>
              </li>
              <li class="footer">
                <a href="#">View all tasks</a>
              </li>
            </ul>
          </li>--}}
          <!-- User Account Menu -->
          <li class="dropdown user user-menu">
            <!-- Menu Toggle Button -->
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <!-- The user image in the navbar-->
              {{-- session('user')->name --}}
              <!-- hidden-xs hides the username on small devices so only the image appears. -->
              <span class="hidden-xs">{{-- "Auth::user()->name" --}}</span>
            </a>
            <ul class="dropdown-menu">
              <!-- The user image in the menu -->
              <li class="user-header">
                <img src="{{asset('public/student_image/user.png')}}" class="img-circle" alt="{{-- session('user')->name --}}">

                <p>
                  {{-- session('user')->name --}}
                </p>
              </li>
              <!-- Menu Body -->
              <li class="user-body">
                <div class="row">
                  <div class="col-xs-4 text-center">
                    <a href="#"></a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#"></a>
                  </div>
                  <div class="col-xs-4 text-center">
                    <a href="#"></a>
                  </div>
                </div>
                <!-- /.row -->
              </li>
              <!-- Menu Footer-->
              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                                        <a href="{{ "url('/logout')" }}"  class="btn btn-default btn-flat"
                                            onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                            Logout
                                        </a>

                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->
          
        </ul>
      </div>
    </nav>
  </header>

  <!-- Main Header -->

resources/views/backend/layout/partials/scripts.blade.php
<!-- REQUIRED JS SCRIPTS -->

<!-- AdminLTE App -->
<script src="{{asset('admin_assets')}}/dist/js/app.min.js"></script>
<script src="{{asset('admin_assets')}}/dist/js/vue.min.js"></script>

@stack('scripts')

<script>
    window.Laravel = {!! json_encode([
        'csrfToken' => csrf_token(),
    ]) !!};
</script>

resources/views/backend/layout/partials/sidebar.blade.php
<aside class="main-sidebar">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <div class="pull-left image">
                <!-- <img src="{{asset('public/student_image/user.png')}}" class="img-circle" alt="User Image"> -->
            </div>
            <div class="pull-left info">
            </div>
        </div>

        <!-- search form (Optional) -->
        <!-- <form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search...">
                <span class="input-group-btn">
                    <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                    </button>
                </span>
            </div>
        </form> -->
        <!-- /.search form -->

        <!-- Sidebar Menu -->
        <ul class="sidebar-menu">
            
            <li class="header"></li>
            
            <li class="{{ request()->is('/') ? 'active' : '' }}"><a href="{{url('/')}}"><i class="fa fa-lg fa-home"></i> <span>Dashboard</span></a></li>
            
            <li class="treeview">
                <a href="#"> <span>Operations</span></a>
            </li>

            <li class="{{ request()->is('*/categories*') ? 'active' : '' }}"><a href="{{ route('categories.index') }}"><i class="ion fa-lg ion-bag "></i><span>Categories</span></a></li>

            <li class="treeview {{ request()->is('*/products*') ? 'active' : '' }}">
                <a href="{{ route('products.index') }}">
                    <i class="ion fa-lg ion-bag"></i><span>Products</span>
                    <i class="fa fa-lg fa-angle-left pull-right"></i>
                </a>
                <ul class="treeview-menu">
                    <li class="{{ request()->fullUrlIs(route('products.index')) ? 'active' : '' }}"><a href="{{ route('products.index') }}"><i class="fa fa-lg fa-list-ul text-orange "></i> All Products</a></li>
                    <li class="{{ request()->fullUrlIs(route('products.create')) ? 'active' : '' }}"><a href="{{ route('products.create') }}"><i class="fa fa-lg fa-plus text-green"></i> Add Product</a></li>
               </ul>
            </li>

            <li class="">
                <a href="{{ route('product-entry-records.index') }}">
                    <i class="ion fa-lg ion-bag"></i><span>Products Entry Records</span>
                </a>
            </li>
            <li class="">
                <a href="{{ route('customer-orders.index') }}">
                    <i class="ion fa-lg ion-bag"></i><span>Bills</span>
                </a>
            </li>

            {{-- <li class="treeview ">
              <a href="#">
                <i class="fa fa-edit"></i> <span>Forms</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li><a href="general.html"><i class="fa fa-circle-o"></i> General Elements</a></li>
                <li><a href="advanced.html"><i class="fa fa-circle-o"></i> Advanced Elements</a></li>
                <li class="active"><a href="editors.html"><i class="fa fa-circle-o"></i> Editors</a></li>
              </ul>
            </li> --}}
     

            
            <!-- <li><a href="#"><i class="fa fa-link"></i> <span>Another Link</span></a></li> -->
            
        </ul>
        
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>