routes/web.php
<?php

// |||||||||||||||||WebView|||||||||||||||||||||
Auth::routes();
Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
	Route::get('/login/callback/{social}', 'SocialAuthController@handleProviderCallback');
	Route::get('/login/{social}', 'SocialAuthController@redirectToProvider');
});
Route::get('/', 'HomeController@index');
Route::get('/category/{name}', 'HomeController@byCategory');
Route::get('/related-products/{categoryId}', 'HomeController@relatedProducts');
Route::get('/detail/{product}', 'HomeController@detail')->name('product.detail');
Route::get('/search', 'HomeController@search')->name('search');
//static
Route::get('/help', 'HomeController@help')->name('help');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/return-policy', 'HomeController@returnPolicy')->name('return-policy');
//cart
Route::get('/cart', 'CartsController@cart');
Route::get('/cart/add/{manage}', 'CartsController@add');
Route::get('/cart/update/{rowId}/{quantity}', 'CartsController@update');
Route::get('/cart/delete/{rowId}', 'CartsController@delete');
Route::get('/cart/destroy', 'CartsController@destroy');

Route::get('/my-cart', 'CartsController@myCart')->name('my-cart');

Route::middleware(['auth'])->group(function () {
	Route::get('/shipping', 'CheckoutsController@shipping')->name('shipping');
	Route::post('/shipping', 'CheckoutsController@storeShipping')->name('shipping.store');
	Route::get('/payment', 'CheckoutsController@payment')->name('payment');
	Route::post('/payment', 'CheckoutsController@storePayment');
	Route::get('/review-order', 'CheckoutsController@reviewOrder')->name('review-order');
	Route::post('/confirm-order', 'CheckoutsController@confirmOrder')->name('confirm-order');
	Route::get('/order-history', 'OrderHistoriesController@orderHistory')->name('order-history');
	Route::get('/order-history/details/{order}', 'OrderHistoriesController@orderDetails')->name('order-history.details');
	Route::get('/user/settings', 'SettingsController@index')->name('settings');
	Route::post('/user/settings', 'SettingsController@updateUser')/*->name('update-user')*/;
 });






// |||||||||||||||||||||admin routes|||||||||||||||||||
Route::prefix('backend')->group(function () {
	Route::get('dashboard', 'BackendController@index')->name('backend');
	Route::get('home', 'BackendController@index');

	Route::resource('categories', 'CategoriesController');

	Route::delete('products/{image}/gallery/remove', 'ProductsController@remove')->name('products.gallery.remove');
	Route::match(['get', 'post'], 'products/{product}/gallery', 'ProductsController@gallery')->name('products.gallery');
	Route::resource('products', 'ProductsController');

	Route::get('product/manage/create/{product}', 'ManageProductsController@create')->name('manage.create');
	Route::get('product/manage/{product}', 'ManageProductsController@show')->name('manage.show');
	Route::get('product/manage/{manage}/increase', 'ManageProductsController@increase')->name('manage.increase');
	Route::resource('product/manage', 'ManageProductsController', ['except' => ['create', 'index', 'show']]);

	Route::resource('product-entry-records', 'ProductEntryRecordsController');

	Route::get('customer-orders/{customer_order}/shipping', 'OrdersController@shipping')->name('customer-orders.shipping');
	Route::resource('customer-orders', 'OrdersController');

	// Route::get('add-product', 'ProductsController@create');

});

Route::get('/home', 'HomeController@index')->name('home');

app/ProductEntryRecord.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ProductEntryRecord extends Model
{
    protected $guarded = [];

    public function product()
    {
        return $this->belongsTo(\App\Product::class);
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
   public function index()
   {
   		return view('backend.home');   
   }

}

app/Http/Controllers/ProductEntryRecordsController.php
<?php

namespace App\Http\Controllers;

use App\ProductEntryRecord;
use Illuminate\Http\Request;

class ProductEntryRecordsController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $products = ProductEntryRecord::with('product')->latest()->paginate(5);
        // return $products;
        $title = 'Product Entry Records';
        return view('backend.ProductEntryRecords.index', compact('title', 'products'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\ProductEntryRecord  $ProductEntryRecord
     * @return \Illuminate\Http\Response
     */
    public function show(ProductEntryRecord $ProductEntryRecord)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\ProductEntryRecord  $ProductEntryRecord
     * @return \Illuminate\Http\Response
     */
    public function edit(ProductEntryRecord $ProductEntryRecord)
    {
        $ProductEntryRecord->load('product');
        // dd($product->product->title);
        $title = "Update Product Entry : {$ProductEntryRecord->product->title}";
        return view('backend.ProductEntryRecords.edit', compact('ProductEntryRecord', 'title'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\ProductEntryRecord  $ProductEntryRecord
     * @return \Illuminate\Http\Response
     */
    public function update(ProductEntryRecord $ProductEntryRecord)
    {
        $this->validate(
            request(), 
            [
                'quantity' => 'integer|min:0',
                "price" => "required|numeric",
                "discount" => "nullable|numeric|max:".request('price')
            ], 
            [
                'quantity.min' => 'Quantity Must be greater than zero'
            ]
        );
        $manage = \App\ManageProduct::where('product_id', $ProductEntryRecord->product_id)
                            ->where('size', $ProductEntryRecord->size)     
                            ->where('color', $ProductEntryRecord->color)
                            ->first();
        $decrease = $ProductEntryRecord->quantity - request('quantity');
        // dd($decrease);
        if($manage && ($manage->quantity >= $decrease))
        {
            \DB::beginTransaction();
            try {                    
                $ProductEntryRecord->quantity -= $decrease; 
                $ProductEntryRecord->price     = request('price'); 
                $ProductEntryRecord->discount  = request('discount'); 
                $ProductEntryRecord->save();

                $manage->quantity -= $decrease;
                $manage->price     = request('price'); 
                $manage->discount  = request('discount');                 
                $manage->save();

                \DB::commit();
                return back()->with('success', "Successfully Updated");
                
            } catch (\ception $e) {
                \DB::rollBack();
                return back()->with('warning', 'Something went wrong!!');
            }
        };
        // dd($decrease);
        return back()->with('warning', 'Something went wrong');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\ProductEntryRecord  $ProductEntryRecord
     * @return \Illuminate\Http\Response
     */
    public function destroy(ProductEntryRecord $ProductEntryRecord)
    {
        //
    }
}

resources/views/backend/ProductEntryRecords/edit.blade.php
@extends('backend.layout.master')

@section('title', $title)


@section('main-content') 
@push('css')
@endpush



<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">{{ $title }}</h3>


  </div>
         
  <div class="box-body">
     
  <div class="box-footer">
    <form method="post" action="{{ route('product-entry-records.update', ['product_entry_record' => $ProductEntryRecord->id]) }}" enctype="multipart/form-data">
      
      {{ csrf_field() }}
      {{ method_field("PUT") }}

        <div class="col-md-6 pull-right">
          <img src="{{ asset($ProductEntryRecord->product->front_image) }}" alt="{{ $ProductEntryRecord->product->title }}" />
        </div>
        <div class="col-md-6">  
        <table class="table table-stripped table-responsive">
          <tr>
            <th>Size</th>
            <td>: {{ $ProductEntryRecord->size }}</td>
          </tr>
          <tr>
            <th>Color</th>
            <td>: {{ $ProductEntryRecord->color }}</td>
          </tr>

          @if ($errors->has('price'))
              <tr>
              <td></td>
                <td>
                  <strong style="color: red;">{{ $errors->first('price') }}</strong>
                </td>
              </tr>
          @endif

          <tr>
            <th>Price</th>
            <td>: 
              <input type="number" style="background:{{ $errors->has('price') ? 'red' : 'lightgreen'}};font-weight:bolder;" name="price" value="{{ $ProductEntryRecord->price }}">
              {{-- $ProductEntryRecord->price --}}
            </td>
          </tr>


          @if ($errors->has('discount'))
              <tr>
              <td></td>
                <td>
                  <strong style="color: red;">{{ $errors->first('discount') }}</strong>
                </td>
              </tr>
          @endif

          <tr>
            <th>Discount</th>
            <td>: 
              <input type="number" style="background:{{ $errors->has('discount') ? 'red' : 'lightgreen'}};font-weight:bolder;" name="discount" value="{{ $ProductEntryRecord->discount }}">
              {{-- $ProductEntryRecord->discount --}}
            </td>
          </tr>

          <tr>
            <th>Added</th>
            <td>: {{ $ProductEntryRecord->created_at }}</td>
          </tr>
          <tr>
            <th>Updated</th>
            <td>: {{ $ProductEntryRecord->updated }}</td>
          </tr>
          @if ($errors->has('quantity'))
              <tr>
              <td></td>
                <td>
                  <strong style="color: red;">{{ $errors->first('quantity') }}</strong>
                </td>
              </tr>
          @endif
          <tr>
            <th>Quantity</th>
            <th>: <input type="number"  autofocus style="background:{{ $errors->has('quantity') ? 'red' : 'lightgreen'}};font-weight:bolder;" name="quantity" value="{{ $ProductEntryRecord->quantity }}"></th>
          </tr>

          <tr>
            <td></td>
            <td><button type="submit" class="btn btn-warning "><i class="fa fa-edit fa-lg"></i>Change</button></td>
          </tr>
        </table>
        </div>
      </form>
  </div>

  </div>
</div>



@push('scripts')
@endpush
@endsection

resources/views/backend/ProductEntryRecords/index.blade.php
@extends('backend.layout.master')

@section('title', $title)

@section('main-content') 

@push('css')
<!-- DataTables -->
<link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.css">
<style type="text/css">
    th { vertical-align: top; }
</style>
@endpush

<div class="box">
    <div class="box-header">
        <h3 class="box-title">{{ $title }}</h3>

    </div>
    <!-- /.box-header -->
    <div class="box-body">

    

        <table id="example1" class="table table-bordered table-striped text-center">
            <thead>
                <tr class="">
                    <th>ID</th>
                    <th>Product</th>
                    <th>Image</th>
                    <th>size</th>
                    <th>color</th>
                    <th>quantity</th>
                    <th>Price (Front)</th>
                    <th>Discount (Front)</th>
                    <th>Added in</th>
                    <th>Actions</th>
                </tr>
            </thead>
            <tbody>
                @if($products)
                @foreach($products as $product)

                <tr>
                    <td>{{ $product->id }}</td>
                    <td>{{ $product->product->title }}</td>
                    <td><img src="{{ asset($product->product->front_image) }}" width="40" /></td>
                    <td>{{ $product->size }}</td>
                    <td>{{ $product->color }}</td>
                    <td>{{ $product->quantity }}</td>
                    <td>{{ $product->price }}</td>
                    <td>{{ $product->discount }}</td>
                    <td>{{ $product->created_at }}</td>
                    <td>
                      <div class="col-sm-8">
                       {{-- <form class="form-inline" action="{{ route('products.destroy', ['product' => $product->id]) }}" method="post">
                          {{ csrf_field() }}
                          {{ method_field('DELETE') }}
                          <button type="submit" class="btn-sm btn-danger pull-right edit" onclick="return confirm('Are you sure')">
                              <i class="glyphicon glyphicon-edit"></i> Delete
                          </button>
                       </form> --}}
                     </div>
                      {{-- <a href="" class="btn-sm btn-danger pull-right edit">
                          <i class="glyphicon glyphicon-trash"></i> Delete
                      </a> --}}
                      <a href="{{ route('product-entry-records.edit', ['product_entry_record' => $product->id ] ) }}" class="btn-sm btn-warning pull-right edit">
                          <i class="glyphicon glyphicon-edit"></i> Edit
                      </a>
                      {{-- <a href="http://localhost:8001/admin/posts/1" class="btn-sm btn-warning pull-right">
                          <i class="glyphicon glyphicon-eye-open"></i> View
                      </a> --}}
                    </td>
                    
                </tr>
                @endforeach
                @endif


            </tbody>

        </table>
     
        <div class="text-center">{{ $products->links() }}</div>
    </div>
    <!-- /.box-body -->
</div>
<!-- /.box -->


@push('scripts')
<!-- DataTables -->
<script src="{{asset('admin_assets')}}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- page script -->
<script>
        $(function () {
        // $("#example1").DataTable();
          $('#example1').DataTable({
                  "paging": false,
                  "lengthChange": false,
                  "searching": true,
                  "ordering": true,
                  "info": true,
                  "autoWidth": false,
                  "columns": [
                  { "searchable": true },
                  { "searchable": true },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  { "searchable": false },
                  ]
          });

        });
</script>
@endpush
@endsection