routes/web.php
<?php

// |||||||||||||||||WebView|||||||||||||||||||||
Auth::routes();
Route::group(['middleware' => 'guest', 'namespace' => 'Auth'], function () {
	Route::get('/login/callback/{social}', 'SocialAuthController@handleProviderCallback');
	Route::get('/login/{social}', 'SocialAuthController@redirectToProvider');
});
Route::get('/', 'HomeController@index');
Route::get('/category/{name}', 'HomeController@byCategory');
Route::get('/related-products/{categoryId}', 'HomeController@relatedProducts');
Route::get('/detail/{product}', 'HomeController@detail')->name('product.detail');
Route::get('/search', 'HomeController@search')->name('search');
//static
Route::get('/help', 'HomeController@help')->name('help');
Route::get('/contact-us', 'HomeController@contactUs')->name('contact-us');
Route::get('/privacy-policy', 'HomeController@privacyPolicy')->name('privacy-policy');
Route::get('/terms', 'HomeController@terms')->name('terms');
Route::get('/return-policy', 'HomeController@returnPolicy')->name('return-policy');
//cart
Route::get('/cart', 'CartsController@cart');
Route::get('/cart/add/{manage}', 'CartsController@add');
Route::get('/cart/update/{rowId}/{quantity}', 'CartsController@update');
Route::get('/cart/delete/{rowId}', 'CartsController@delete');
Route::get('/cart/destroy', 'CartsController@destroy');

Route::get('/my-cart', 'CartsController@myCart')->name('my-cart');

Route::middleware(['auth'])->group(function () {
	Route::get('/shipping', 'CheckoutsController@shipping')->name('shipping');
	Route::post('/shipping', 'CheckoutsController@storeShipping')->name('shipping.store');
	Route::get('/payment', 'CheckoutsController@payment')->name('payment');
	Route::post('/payment', 'CheckoutsController@storePayment');
	Route::get('/review-order', 'CheckoutsController@reviewOrder')->name('review-order');
	Route::post('/confirm-order', 'CheckoutsController@confirmOrder')->name('confirm-order');
	Route::get('/order-history', 'OrderHistoriesController@orderHistory')->name('order-history');
	Route::get('/order-history/details/{order}', 'OrderHistoriesController@orderDetails')->name('order-history.details');
	Route::get('/user/settings', 'SettingsController@index')->name('settings');
	Route::post('/user/settings', 'SettingsController@updateUser')/*->name('update-user')*/;
 });






// |||||||||||||||||||||admin routes|||||||||||||||||||
Route::prefix('backend')->group(function () {
	Route::get('dashboard', 'BackendController@index')->name('backend');
	Route::get('home', 'BackendController@index');

	Route::resource('categories', 'CategoriesController');

	Route::delete('products/{image}/gallery/remove', 'ProductsController@remove')->name('products.gallery.remove');
	Route::match(['get', 'post'], 'products/{product}/gallery', 'ProductsController@gallery')->name('products.gallery');
	Route::resource('products', 'ProductsController');

	Route::get('product/manage/create/{product}', 'ManageProductsController@create')->name('manage.create');
	Route::get('product/manage/{product}', 'ManageProductsController@show')->name('manage.show');
	Route::get('product/manage/{manage}/increase', 'ManageProductsController@increase')->name('manage.increase');
	Route::resource('product/manage', 'ManageProductsController', ['except' => ['create', 'index', 'show']]);

	Route::resource('product-entry-records', 'ProductEntryRecordsController');

	Route::get('customer-orders/{customer_order}/shipping', 'OrdersController@shipping')->name('customer-orders.shipping');
	Route::resource('customer-orders', 'OrdersController');

	// Route::get('add-product', 'ProductsController@create');

});

Route::get('/home', 'HomeController@index')->name('home');

app/Category.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Category extends Model
{
    public $timestamps = false;
    protected $fillable = ['name'];

    public function product()
    {
        return $this->hasMany(\App\Product::class);
    }
}

app/Http/Controllers/BackendController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class BackendController extends Controller
{
   public function index()
   {
   		return view('backend.home');   
   }

}

app/Http/Controllers/CategoriesController.php
<?php

namespace App\Http\Controllers;

use App\Category;
use Illuminate\Http\Request;

class CategoriesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $categories = Category::all();
        return view('backend.Categories.index', compact('categories'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('backend.Categories.category');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
                'name' => 'required|unique:categories,name'
            ], [
                // 'name.required' => 'here u go'
            ]);
        $category = Category::create(['name' => $request->name]);
        return back()->with('success', "Successfully added {$category->name}");
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function show(Category $category)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function edit(Category $category)
    {
        // dd($category);
        return view('backend.Categories.edit', compact('category'))->withTitle('Edit Category');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function update(Category $category)
    {
        $this->validate(request(), ['name' => 'unique:categories,name']);
        $category->update(['name' => request('name')]);
        return redirect()->route('categories.index')->with("success", "Successfully updated {$category->name}");
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Category  $category
     * @return \Illuminate\Http\Response
     */
    public function destroy(Category $category)
    {
        if($category->product()->count() > 0 )
            return back()->with('danger', 'Can\'t be deleted as this category have products');

        $category->delete();
        return back()->with('success', "successfully deleted");
    }
}

resources/views/backend/Categories/add-category.blade.php
@extends('backend.layout.master')

@section('title', 'Sale Records')


@section('main-content')
@push('css')
  <!-- DataTables -->
  <link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.css">
  <!-- bootstrap datepicker -->
  <link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/datepicker/datepicker3.css">
  <!-- Select2 -->
  <!-- <link rel="stylesheet" href="{{asset('admin_assets')}}/plugins/select2/select2.min.css"> -->
  <style type="text/css">
    th { vertical-align: top; }
  </style>
@endpush




===============
{{ Request::current() }}




@push('scripts')
<!-- DataTables -->
<script src="{{asset('admin_assets')}}/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="{{asset('admin_assets')}}/plugins/datatables/dataTables.bootstrap.min.js"></script>
<!-- bootstrap datepicker -->
<script src="{{asset('admin_assets')}}/plugins/datepicker/bootstrap-datepicker.js"></script>
<!-- Select2 -->
<!-- <script src="{{asset('admin_assets')}}/plugins/select2/select2.full.min.js"></script> -->
<!-- page script -->
<script>
  $(function () {
    // $("#example1").DataTable();
    $('#example1').DataTable({
      "paging": false,
      "lengthChange": false,
      "searching": true,
      "ordering": false,
      "info": true,
      "autoWidth": false,
      "columns": [
        { "searchable": true },
        { "searchable": true },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
        { "searchable": false },
      ] 
    });


    //Initialize Select2 Elements
    // $(".select2").select2();

    //Date picker
    $('#datepicker1').datepicker({
      autoclose: true,
      format: 'yyyy-mm-dd'
    });
    $('#datepicker2').datepicker({
      autoclose: true,
      format: 'yyyy-mm-dd'
    });


    @if(isset($product_id))
      $('#product_id').val('{{ $product_id }}');
    @endif


  });
  </script>
@endpush
@endsection

resources/views/backend/Categories/edit.blade.php
@extends('backend.layout.master')

@section('title', $title)


@section('main-content')
@push('css')

@endpush




<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">{{ $title }}</h3>

  </div>

  <div class="box-footer{{ $errors->has('name') ? ' has-error' : '' }}">
    <form method="post" action="{{ route('categories.update', ['category' => $category->id ]) }}">
      {{ csrf_field() }}
       {{ method_field('PUT') }}
      <div class="input-group input-group-lg">
        <input name="name" type="text" value="{{ $category->name }}" class="form-control" required>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-warning btn-flat"><i class="fa fa-wrench"></i> Update</button>
        </span>
      </div>

       @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
      </form>
  </div>
</div>

@push('scripts')
@endpush
@endsection

resources/views/backend/Categories/index.blade.php
@extends('backend.layout.master')

@section('title', 'Categories')


@section('main-content')
@push('css')

@endpush




<div class="box box-success">

  <div class="box-header ui-sortable-handle" style="cursor: move;">
    <i class="fa fa-th"></i>

    <h3 class="box-title">Add Category</h3>

  </div>

  <div class="box-footer{{ $errors->has('name') ? ' has-error' : '' }}">
    <form method="post" action="{{ route('categories.store') }}">
      {{ csrf_field() }}
      <div class="input-group input-group-lg">
        <input name="name" type="text" value="{{ old('name') }}" class="form-control" placeholder="Type a category..." required>
        <span class="input-group-btn">
          <button type="submit" class="btn btn-success btn-flat"><i class="glyphicon glyphicon-plus"></i> Add</button>
        </span>
      </div>

       @if ($errors->has('name'))
            <span class="help-block">
                <strong>{{ $errors->first('name') }}</strong>
            </span>
        @endif
      </form>
  </div>
</div>


<div class="box box-primary">
            <div class="box-header ui-sortable-handle" style="cursor: move;">
              <i class="ion ion-clipboard"></i>

              <h3 class="box-title">Categoies</h3>

            </div>
            <!-- /.box-header -->
            <form method="post">
            {{ csrf_field() }}
            <div class="box-body">
              <ul class="todo-list ui-sortable">
                @foreach($categories as $category)
                <li class="">
                      <span class="handle ui-sortable-handle">
                        {{ $loop->iteration }} &nbsp;
                        <i class="fa fa-ellipsis-v"></i>
                        <i class="fa fa-ellipsis-v"></i>
                      </span>
                  <!-- checkbox -->
                  {{-- <input name="id[]" type="checkbox" value="{{ $category->id }}"> --}}
                  <!-- todo text -->
                  <span class="text">{{ $category->name }}</span>
                  {{-- <input class=" edit-{{ $category->id }}" type="text" name="name" value="{{ $category->name }}"> --}}
                  <!-- General tools such as edit or delete-->
                  <div class="tools">
                    <a href="{{ route('categories.edit', [ 'category' => $category->id]) }}"><span class="fa fa-2x fa-edit btn-edit-{{ $category->id }}" data-toggle="tooltip" title="Edit"></span></a>
                    <a href="#" onclick="delete_category('{{ route('categories.destroy', [ 'category' => $category->id]) }}')"><sapn class="fa fa-2x fa-trash-o bg-red" data-toggle="tooltip" title="delete"></sapn></a>
                  </div>
                </li>
                @endforeach
              </ul>
            </div>
            <!-- /.box-body -->
            </form>
          </div>


        <form id="delete-form" method="post">
          {{ csrf_field() }}
          {{ method_field('DELETE') }}
        </form>

@push('scripts')
<script>
$(".todo-list > li .tools button").click(function(event){
    event.preventDefault();
});
function delete_category(url) {
  if ( confirm('are you sure'))
  {
    $('#delete-form').attr('action', url);
    $('#delete-form').submit();
  }
}
</script>
@endpush
@endsection